server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pfe
    username: root

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org.springframework.web: DEBUG
    ma.pfe: DEBUG
    org.hibernate: INFO